
###
GET http://localhost:3000/posts

###
GET http://localhost:3000/posts?Sender=itzik

###

GET http://localhost:3000/posts/6744d0aa205cfa5f8a9bca85

###

POST http://localhost:3000/posts 
Content-Type: application/json

{
"title": "mr 3",
"Sender": "meni",
"content": "this project worth 100"
}

###

PUT http://localhost:3000/posts/6744d0aa205cfa5f8a9bca85
Content-Type: application/json

{
  "title": "Updated Title",
  "content": "This is the updated content"
}
